npm i --save vue
npm i --save vue-router
npm i --save-dev autoprefixer
npm i --save-dev babel-core
npm i --save-dev babel-helper-vue-jsx-merge-props
npm i --save-dev babel-loader
npm i --save-dev babel-plugin-syntax-jsx
npm i --save-dev babel-plugin-transform-runtime
npm i --save-dev babel-plugin-transform-vue-jsx
npm i --save-dev babel-preset-env
npm i --save-dev babel-preset-stage-2
npm i --save-dev chalk
npm i --save-dev copy-webpack-plugin
npm i --save-dev css-loader
npm i --save-dev extract-text-webpack-plugin
npm i --save-dev file-loader
npm i --save-dev friendly-errors-webpack-plugin
npm i --save-dev html-webpack-plugin
npm i --save-dev node-notifier
npm i --save-dev optimize-css-assets-webpack-plugin
npm i --save-dev ora
npm i --save-dev portfinder
npm i --save-dev postcss-import
npm i --save-dev postcss-loader
npm i --save-dev postcss-url
npm i --save-dev rimraf
npm i --save-dev semver
npm i --save-dev shelljs
npm i --save-dev uglifyjs-webpack-plugin
npm i --save-dev url-loader
npm i --save-dev vue-loader
npm i --save-dev vue-style-loader
npm i --save-dev vue-template-compiler
npm i --save-dev webpack
npm i --save-dev webpack-bundle-analyzer
npm i --save-dev webpack-dev-server
npm i --save-dev webpack-merge
